import { IColumn } from "@fluentui/react";

export const columns: IColumn[] = [
    {
        key: "column1",
        name: "DATASET NAME",
        ariaLabel: "Column operations for File type, Press to sort on File type",
        isResizable: true,
        fieldName: "datasetName",
        minWidth: 110,
        maxWidth: 200,
    },
    {
        key: "column2",
        name: "Creation Date",
        fieldName: "dateCreatedValue",
        minWidth: 132,
        maxWidth: 132,
        isResizable: true,
        // onColumnClick: this._onColumnClick,
        // data: 'date',
    },
    {
        key: "column3",
        name: "Related Publication",
        fieldName: "relatedPublication",
        minWidth: 198,
        maxWidth: 198,
        isResizable: true,
    },
    {
        key: "column4",
        name: "Publication Date",
        fieldName: "datePublishedValue",
        minWidth: 148,
        maxWidth: 148,
        isResizable: true,
        // onColumnClick: this._onColumnClick,
        // data: 'number',
    },
    {
        key: "column5",
        name: "File Count",
        fieldName: "fileCount",
        minWidth: 89,
        maxWidth: 109,
        isResizable: true,
        data: "number",
    },
    {
        key: "column6",
        name: "Size",
        fieldName: "size",
        minWidth: 78,
        maxWidth: 98,
        isResizable: true,
    },
    {
        key: "column7",
        name: "Description",
        fieldName: "description",
        minWidth: 118,
        maxWidth: 224,
        isResizable: true,
    },
];
