import { TOP_LEVEL_FILE_ANNOTATION_NAMES } from "../../../constants";

export default new Set([
    ...TOP_LEVEL_FILE_ANNOTATION_NAMES,
    "Cache Eviction Date",
    "Cas9",
    "Cas9 Batch",
    "Cell Batch",
    "Cell Line",
    "Cell Line R And D",
    "Cell Line Source",
    "Cell Population Id",
    ,
    "Channel Number 405",
    "Channel Number 638",
    "Channel Number Brightfield",
    "Channel Number Struct",
    "Channel Type",
    "Clone",
    "Cr Rna",
    "Cr Rna Batch",
    "Diff Scientist",
    "Donor Plasmid",
    "Donor Plasmid Batch",
    "Fov",
    "Kind",
    "Should Be in Local Cache",
    "Structure",
    "Tag Location",
    "Type",
    "Fluorescent Protein",
    "Fov",
    "Gene",
    "Passage",
    "Plate Batch",
    "Plate Geometry",
    "Plate Layout",
    "Plate Seeded On",
    "Plate Status",
    "Plate Type",
    "Protein",
    "Protocol",
    "Protocol Applied",
    "QC Pass Intensity",
    "QC Brightfield Z Stack Out of Order",
    "QC 638nm Crop Bottom False Clip",
    "QC 638nm Crop Top False Clip",
    "Quality Control Status",
    "Replicate",
    "Solution",
    "Solution Lot Batch Volume",
    "Solution Lot Catalog",
    "Solution Lot Date",
    "Solution Lot Expiration Date",
    "Solution Lot Id",
    "Solution Lot Host",
    "Solution Lot",
    "Solution Lot Stock Concentration",
    "Solution Lot Stock Dilution Factor",
    "Solution Lot Vendor",
    "Solution Volume",
    "Solution Working Concentration",
    "Stage",
    "Target Cell Type",
    "Template",
    "Uploaded by",
    "Well",
    "Well Group",
    "Well Label",
    "Well Type",
    "Workflow",
]);
