/**
 * A verbatim capture of the transaction log delta-rs writes, kept so the
 * in-memory table builder in these tests is checked against something a real
 * writer produced rather than only against our own idea of the format.
 *
 * Generated by deltalake 1.5.0: write, append, then `DELETE WHERE a = 1`.
 * Commit 1's file is added and commit 2 removes it, so the live snapshot is the
 * single file added by commit 0.
 */
export const DELTA_RS_LOG: Record<string, string> = {
    "00000000000000000000.json":
        '{"commitInfo":{"timestamp":1787166946503,"operation":"WRITE","operationParameters":{"mode":"Overwrite"},"engineInfo":"delta-rs:py-1.5.0","clientVersion":"delta-rs.py-1.5.0","operationMetrics":{"execution_time_ms":50,"num_added_files":1,"num_added_rows":1,"num_partitions":0,"num_removed_files":0}}}\n{"protocol":{"minReaderVersion":1,"minWriterVersion":2}}\n{"metaData":{"id":"9c410a16-6c38-4b12-b09b-b0c302c02bb8","name":null,"description":null,"format":{"provider":"parquet","options":{}},"schemaString":"{\\"type\\":\\"struct\\",\\"fields\\":[{\\"name\\":\\"a\\",\\"type\\":\\"long\\",\\"nullable\\":true,\\"metadata\\":{}}]}","partitionColumns":[],"createdTime":1787166946455,"configuration":{}}}\n{"add":{"path":"part-00000-0bf6d017-ca81-4011-ad44-2cbff9184637-c000.snappy.parquet","partitionValues":{},"size":484,"modificationTime":1787166946502,"dataChange":true,"stats":"{\\"numRecords\\":1,\\"minValues\\":{\\"a\\":1},\\"maxValues\\":{\\"a\\":1},\\"nullCount\\":{\\"a\\":0}}","tags":null,"baseRowId":null,"defaultRowCommitVersion":null,"clusteringProvider":null}}',
    "00000000000000000001.json":
        '{"commitInfo":{"timestamp":1787166946534,"operation":"WRITE","operationParameters":{"mode":"Append"},"engineInfo":"delta-rs:py-1.5.0","clientVersion":"delta-rs.py-1.5.0","operationMetrics":{"execution_time_ms":8,"num_added_files":1,"num_added_rows":1,"num_partitions":0,"num_removed_files":0}}}\n{"add":{"path":"part-00000-4bace493-18e2-4111-8b16-6e8e79490778-c000.snappy.parquet","partitionValues":{},"size":484,"modificationTime":1787166946534,"dataChange":true,"stats":"{\\"numRecords\\":1,\\"minValues\\":{\\"a\\":2},\\"maxValues\\":{\\"a\\":2},\\"nullCount\\":{\\"a\\":0}}","tags":null,"baseRowId":null,"defaultRowCommitVersion":null,"clusteringProvider":null}}',
    "00000000000000000002.json":
        '{"commitInfo":{"timestamp":1787166946585,"operation":"DELETE","operationParameters":{"predicate":"a = 1"},"engineInfo":"delta-rs:py-1.5.0","operationMetrics":{"execution_time_ms":29,"num_added_files":0,"num_copied_rows":0,"num_deleted_rows":1,"num_removed_files":1,"rewrite_time_ms":0,"scan_time_ms":27},"clientVersion":"delta-rs.py-1.5.0","readVersion":1}}\n{"remove":{"path":"part-00000-0bf6d017-ca81-4011-ad44-2cbff9184637-c000.snappy.parquet","dataChange":true,"deletionTimestamp":1787166946583,"extendedFileMetadata":true,"partitionValues":{},"size":484}}',
};

/** The one file still live after that history, per the reference reader. */
export const DELTA_RS_LIVE_FILE =
    "part-00000-4bace493-18e2-4111-8b16-6e8e79490778-c000.snappy.parquet";
